<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <script>
    //async函数的返回值是一个promise对象
    //async函数返回的promise的结果由函数执行的结果决定
    // async function fn1() {
    // return 1
    //产生一个失败 promise
    // throw 2
    // return Promise.reject(3)
    // return Promise.resolve(3)
    //   return new Promise((resolve, reject) => {
    //     setTimeout(() => {
    //       resolve(4)
    //     }, 1000);
    //   })
    // }
    // const result = fn1()
    // // console.log(result)
    // result.then(
    //   value => {
    //     console.log('onResolved()', value);
    //   },
    //   reason => {
    //     console.log('onRejected()', reason);

    //   }
    // )

    function fn2() {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(5)
        }, 1000);
      })
    }
    function fn4() {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          reject(6)
        }, 1000);
      })

    }
    async function fn3() {
      //不一定放promise对象 // await右侧表达式为promise，得到的结果就是promise成功的value
      // const value = await fn2()
      // const value = await 6//await右侧表达式不是promise,得到的结果就是它本身

      try {
        const value = await fn4()//得到失败的结果，用trycatch
        // console.log('value', value);
      } catch (error) {
        console.log('失败的结果', error);

      }

    }
    fn3()
  </script>
</body>

</html>